### ISSUE TITLE
面板报错

### ISSUE THREAD

**Issue by myitmx** [Netrvin/CFPMP#1]
![qq 20180518111543](https://user-images.githubusercontent.com/19377656/40214395-0bb207e6-5a8d-11e8-9ba7-2f07f3c8f8d0.png)
这个应该怎么解决

**Comment by Netrvin** [comment]
这个不影响使用的，在php.ini里面把error_reporting设置成不输出E_STRICT即可

**Comment by myitmx** [comment]
嗯，我自行修改了一下PHP代码

**Comment by Netrvin** [comment]
能pull request一下吗？谢谢

**Comment by myitmx** [comment]
emmm......我把修改后的文件直接打包发到我博客了： https://www.myitmx.com/600.html
