### ISSUE TITLE
API 是否可以开启5秒盾 

### ISSUE THREAD

**Issue by Guang0** [Netrvin/CFPMP#3]
免费版的唯一这个功能最实用了 是否可以开启 如果可以的话 我应该怎么做？

**Comment by Guang0** [comment]
API 好像没有 也不可以集成这个功能 但是一切都可以登录到CF去修改 如果可以继承到API里面就更好了

**Comment by Netrvin** [comment]
你可以浏览 https://api.cloudflare.com/ 这个网站查看API是否支持开启此功能
