### ISSUE TITLE
添加失败无法返回错误信息

### ISSUE THREAD

**Issue by huanjue** [Netrvin/CFPMP#6]
另外一个面板（这个面板就叫CloudFlare Partner）在添加域名失败后会显示失败详情。
CFPMP显示添加失败，但并不显示失败详情。

**Comment by Netrvin** [comment]
请问是在什么情况下添加失败不显示详情？我这里无法复现
![img_20180817_105624](https://user-images.githubusercontent.com/11222509/44245647-5558f280-a20c-11e8-9a32-96ebd4997085.jpg)

**Comment by huanjue** [comment]
https://s33.postimg.cc/8lykfeir3/image.png
添加一个处于serverhold状态的域名或者是添加一个根本不存在的域名时。
另一款面板显示的是域名没有注册，而CFPMP显示空白信息。
我看了下cf.class.php没啥问题，不知道为什么会无法显示。
