### ISSUE TITLE
Cloudflare Partner API Remove Support for 2FA

### ISSUE THREAD

**Issue by SukkaW** [Netrvin/CFPMP#9]
Current API endpoint no longer support user with 2FA enabled. Any attempt to login will result in error message:

```
登陆 / 注册失败：Cannot link the Cloudflare account which has two-factor authentication enabled
```

**Comment by du5** [comment]
+1

**Comment by Netrvin** [comment]
Hosting Provider API 中未提供 2FA 相关 API ，同时，因为 131 最近比较忙，暂时没有时间去寻找解决方法，建议先尝试自行解决或关闭 2FA
